language: python
python:
    - 3.5
    - 3.4
    - 3.3
    - 2.7
sudo: false
before_install:
    - pip install -r requirements.txt -r test_requirements.txt
install:
    - pip install -e .
script:
    - py.test -l --cov=nbdime
after_success:
    - coveralls
