language: python
python:
  - 3.5
  - 3.4
  - 3.3
  - 2.7
sudo: false
env:
  matrix:
    - GROUP=python
matrix:
  include:
    - python: 3.5
      env: GROUP=js
cache:
  pip: true
  directories:
    - nbdime/webapp/node_modules # NPM packages
    - nbdime-web/node_modules # NPM packages
before_install:
  - nvm install 4
  - |
    if [[ $GROUP == python ]]; then
      pip install codecov
    elif [[ $GROUP == js ]]; then
      npm install -g codecov
    fi
install:
  - pip install --upgrade -e ".[test]"
  - |
    if [[ $GROUP == js ]]; then
      cd nbdime-web
      npm install
    fi
before_script:
  # Set up a virtual screen for Firefox browser testing:
  - |
    if [[ $GROUP == js ]]; then
      export CHROME_BIN=chromium-browser
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
    fi
script:
  - |
    if [[ $GROUP == python ]]; then
      py.test -l --cov-report html --cov=nbdime
    elif [[ $GROUP == js ]]; then
      npm test
    fi
after_success:
    - 'if [[ $GROUP == js ]]; then cd ..; fi'
    - codecov
before_cache:
  # Do not cache our own package
  - rm -rf nbdime/webapp/node_modules/nbdime
  - rm -rf nbdime/webapp/node_modules/nbdime-webapp
  - rm -rf nbdime-web/node_modules/nbdime
